//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public class Items {
    
    private ItemsItem[] itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Item")]
    public ItemsItem[] Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public class ItemsItem {
    
    private int itemIdField;
    
    private string itemDescField;
    
    private ItemsItemAnswer[] answersField;

    private int selectedAnswerIdField;

    private int correctAnswerIdField;

    private ItemTypeEnum itemTypeField;
    
    /// <remarks/>
    public int ItemId
    {
        get {
            return this.itemIdField;
        }
        set {
            this.itemIdField = value;
        }
    }
    
    /// <remarks/>
    public string ItemDesc {
        get {
            return this.itemDescField;
        }
        set {
            this.itemDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Answer", IsNullable=false)]
    public ItemsItemAnswer[] Answers {
        get {
            return this.answersField;
        }
        set {
            this.answersField = value;
        }
    }
    
    /// <remarks/>
    public int SelectedAnswerId
    {
        get {
            return this.selectedAnswerIdField;
        }
        set {
            this.selectedAnswerIdField = value;
        }
    }
    
    /// <remarks/>
    public int CorrectAnswerId
    {
        get {
            return this.correctAnswerIdField;
        }
        set {
            this.correctAnswerIdField = value;
        }
    }
    
    /// <remarks/>
    public ItemTypeEnum ItemType
    {
        get {
            return this.itemTypeField;
        }
        set {
            this.itemTypeField = value;
        }
    }
}

 public enum ItemTypeEnum
    {
        Pretest,
        Operational
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public class ItemsItemAnswer {

    private int answerIdField;
    
    private string answerDescField;
    
    /// <remarks/>
    public int AnswerId
    {
        get {
            return this.answerIdField;
        }
        set {
            this.answerIdField = value;
        }
    }
    
    /// <remarks/>
    public string AnswerDesc {
        get {
            return this.answerDescField;
        }
        set {
            this.answerDescField = value;
        }
    }
}
